name: nca-toolkit
services:
- name: api
  image:
    registry_type: DOCKER_HUB
    repository: stephengpope/no-code-architects-toolkit
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /v1/system/status
  envs:
  - key: API_KEY
    value: Omar123..
    type: SECRET
  - key: LOCAL_STORAGE_PATH
    value: /tmp
  - key: MAX_QUEUE_LENGTH
    value: "10"
  - key: GUNICORN_WORKERS
    value: "2"
  - key: GUNICORN_TIMEOUT
    value: "600"
